language: csharp
mono: none
dist: xenial
sudo: required
dotnet: 5.0
solution: src/CarRentalSystem.sln
install:
  - dotnet restore
script:
  - cd src
  - dotnet build
branches:
  only:
  - main
  - dev
