language: csharp
mono: none
dist: xenial
sudo: required
dotnet: 5.0
solution: src/CarRentalSystem.sln
before_script:
  - chmod -R a+x scripts
install:
  - ./scripts/dotnet-restore.sh
script:
  - dotnet build
branches:
  only:
  - main
  - dev
