language: csharp
mono: none
dist: xenial
sudo: required
dotnet: 5.0
solution: src/CarRentalSystem.sln
before_install:
  - chmod +x ./scripts/dotnet-restore.sh 
install:
  - travis_wait ./scripts/dotnet-restore.sh
before_script:
  - chmod +x ./scripts/dotnet-build.sh 
script:
  - ./scripts/dotnet-build.sh
branches:
  only:
  - main
  - dev
