language: csharp
mono: none
dist: xenial
sudo: required
dotnet: 5.0
solution: src/CarRentalSystem.sln
install:
  - ./scripts/dotnet-restore.sh
script:
  - dotnet build
branches:
  only:
  - main
  - dev
