version: "3.8"

services:
   data:
      container_name: sqlserver
      image: mcr.microsoft.com/mssql/server:2019-latest
      ports: 
         - "1433:1433"
      environment:
         - ACCEPT_EULA=Y
         - SA_PASSWORD=yourStrongPassword12!@
      volumes: 
         - sqldata:/var/opt/mssql 
      networks: 
         - carrentalsystem-network
         
   identity:
      container_name: identity
      build:
            context: ./src
            dockerfile: ./CarRentalSystem.Identity.API/Dockerfile
      ports: 
            - "5001:80"
      env_file: ./src/CarRentalSystem.Common/Common.env
      environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CarRentalIdentityDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
      restart: on-failure
      volumes:
            - ./.aspnet/identity/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
      networks: 
            - carrentalsystem-network
      depends_on:
            - data

   dealers:
      container_name: dealers
      build:
         context: ./src
         dockerfile: ./CarRentalSystem.Dealers.API/Dockerfile
      ports: 
         - "5003:80"
      env_file: ./src/CarRentalSystem.Common/Common.env
      environment:
         - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CarRentalDealersDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
      restart: on-failure
      volumes:
         - ./.aspnet/dealers/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
      networks: 
         - carrentalsystem-network
      depends_on:
         - data
   
   statistics:
      container_name: statistics
      build:
            context: ./src
            dockerfile: ./CarRentalSystem.Statistics.API/Dockerfile
      ports: 
            - "5005:80"
      env_file: ./src/CarRentalSystem.Common/Common.env
      environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CarRentalStatisticsDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
      restart: on-failure
      volumes:
            - ./.aspnet/statistics/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
      networks: 
            - carrentalsystem-network
      depends_on:
            - data
networks:
   carrentalsystem-network:
volumes:
   sqldata: