version: "3.8"

services:
   data:
      container_name: sqlserver
      image: mcr.microsoft.com/mssql/server:2019-latest
      ports: 
         - "1433:1433"
      environment:
         - ACCEPT_EULA=Y
         - SA_PASSWORD=yourStrongPassword12!@
      volumes: 
         - sqldata:/var/opt/mssql 
      networks: 
         - carrentalsystem-network
       
   messages:
      container_name: rabbitmq
      image: rabbitmq:3-management
      ports:
         - "15672:15672"
         - "5672:5672"
      hostname: "rabbitmq"
      environment:
         - RABBITMQ_ERLANG_COOKIE=Rand0mR4bbitMqCo0k1e
         - RABBITMQ_DEFAULT_USER=rabbitmq
         - RABBITMQ_DEFAULT_PASS=rabbitmq
      networks: 
         - carrentalsystem-network

   identity:
      container_name: identity
      build:
            context: ./src
            dockerfile: ./CarRentalSystem.Identity.API/Dockerfile
      ports: 
            - "5001:80"
      env_file: ./src/CarRentalSystem.Common/Common.env
      environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CarRentalIdentityDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
      restart: on-failure
      volumes:
            - ./.aspnet/identity/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
      networks: 
            - carrentalsystem-network
      depends_on:
            - data

   dealers:
      container_name: dealers
      build:
         context: ./src
         dockerfile: ./CarRentalSystem.Dealers.API/Dockerfile
         args: 
            - Mode=Debug
      ports: 
         - "5003:80"
      env_file: ./src/CarRentalSystem.Common/Common.env
      environment:
         - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CarRentalDealersDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
      restart: on-failure
      volumes:
         - ./.aspnet/dealers/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
      networks: 
         - carrentalsystem-network
      depends_on:
         - data
   
   dealers-gateway:
      container_name: dealers-gateway
      build:
         context: ./src
         dockerfile: ./CarRentalSystem.Dealers.Gateway/Dockerfile
         args: 
            - Mode=Debug
      ports: 
         - "5011:80"
      env_file: ./src/CarRentalSystem.Common/Common.env
      environment:
         - ServiceEndpoints__Statistics=http://statistics
         - ServiceEndpoints__Dealers=http://dealers
      restart: on-failure
      volumes:
         - ./.aspnet/dealers-gateway/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
      networks: 
         - carrentalsystem-network
      depends_on:
         - data
         - dealers
         - statistics
      
   statistics:
      container_name: statistics
      build:
            context: ./src
            dockerfile: ./CarRentalSystem.Statistics.API/Dockerfile
            args: 
               - Mode=Debug
      ports: 
            - "5005:80"
      env_file: ./src/CarRentalSystem.Common/Common.env
      environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CarRentalStatisticsDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
      restart: on-failure
      volumes:
            - ./.aspnet/statistics/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
      networks: 
            - carrentalsystem-network
      depends_on:
            - data

   watchdog:
      container_name: watchdog
      build:
         context: ./src
         dockerfile: ./CarRentalSystem.Watchdog/Dockerfile
      ports: 
         - "5007:80"
      restart: on-failure
      networks: 
         - carrentalsystem-network
      depends_on:
         - identity
         - dealers
         - statistics

   admin:
      container_name: admin
      build:
         context: ./src
         dockerfile: ./CarRentalSystem.Admin/Dockerfile
      ports: 
         - "5009:80"
      env_file: ./src/CarRentalSystem.Common/Common.env
      environment:
         - ServiceEndpoints__Identity=http://identity
         - ServiceEndpoints__Statistics=http://statistics
         - ServiceEndpoints__Dealers=http://dealers
      restart: on-failure  
      depends_on:
         - identity 
         - statistics
         - dealers
      networks: 
         - carrentalsystem-network
networks:
   carrentalsystem-network:
volumes:
   sqldata: